services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql 
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
      LC_ALL: ja_JP.UTF-8
      LANG: ja_JP.UTF-8
    ports:
      - "3306:3306"

  app:
    container_name: tomcat
    image: tomcat:latest
    environment: 
      APP_ENV: prod
    ports:
      - 8080:8080
    volumes:
      - ./webapps:/usr/local/tomcat/webapps

  web:
    container_name: apache
    image: httpd:latest
    ports:
      - 80:80
    volumes:
      - ./conf:/usr/local/apache2/conf

volumes:
    db_data: